### ISSUE TITLE
Cannot use class-based custom encoder

### ISSUE THREAD

**Issue by MeirionHughes** [Level/abstract-level#77]
I'm not sure if this would be a bug as its a new code-base afterall; but its certainly a deviation from the leveldown way, where this worked. 

```js
class CustomEncoding {
  encode (arg) { return JSON.stringify(arg) }
  decode (arg) { return JSON.parse(arg) };
  constructor () {
    this.format = 'utf8'
    this.type = 'custom'
  }
}

const customEncoding = new CustomEncoding()

const db = testCommon.factory({
  keyEncoding: customEncoding,
  valueEncoding: customEncoding
})
```

> TypeError: The 'encode' property must be a function
    at new Encoding (D:\Code\abstract-level\node_modules\level-transcoder\lib\encoding.js:28:13)
    at new UTF8Format (D:\Code\abstract-level\node_modules\level-transcoder\lib\formats.js:75:5)
    at from (D:\Code\abstract-level\node_modules\level-transcoder\index.js:111:25)
    at Transcoder.encoding (D:\Code\abstract-level\node_modules\level-transcoder\index.js:66:20)
    at new AbstractLevel (D:\Code\abstract-level\abstract-level.js:4:432)
    at new MinimalLevel (D:\Code\abstract-level\test\util.js:123:5)
    at Object.factory (D:\Code\abstract-level\test\self.js:1078:12)
    at run (D:\Code\abstract-level\test\encoding-custom-class-test.js:72:27)
    at Test.<anonymous> (D:\Code\abstract-level\test\encoding-custom-class-test.js:7:7)

**Comment by vweevers** [comment]
Yeah that's a bug. I'm guessing it's caused by class properties not being enumerable.

**Comment by vweevers** [comment]
The encoding is cloned as `{ ...options }` here and thus won't include class methods: https://github.com/Level/transcoder/blob/main/index.js#L111

**Comment by MeirionHughes** [comment]
yeah I assumed it was cloning issue. 

I also notice that in Encoding class, it rebinds the option encode and decode functions 'this'. I have configured custom encoder class that changes the decoding (option to skip certain certain parts of the encoded binary and not decode them) - so I suspect that won't work either. 

I can get around this either by wrapping object + closures and/or deriving from abstract class Encoding.

**Comment by MeirionHughes** [comment]
```js 
function safeOptions(base, name){
  return {
    name, 
    format: base.format, 
    encode: function(...args){return base.encode(...args)},
    decode: function(...args){return base.decode(...args)}
  }
}

switch (detectFormat(options)) {
  case 'view': return new ViewFormat(safeOptions(options, name))
  case 'utf8': return new UTF8Format(safeOptions(options, name))
  case 'buffer': return new BufferFormat(safeOptions(options, name))
  default: {
    throw new TypeError("Format must be one of 'buffer', 'view', 'utf8'")
  }
}
```

lets the test (with a class) pass; not sure if you'd rather do it differently
